### ISSUE TITLE
Don't convert input to an array

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/p-map#1]
https://github.com/sindresorhus/p-map/blob/051cf2692fb66dbc05a2ef41101c7fcf6e108207/index.js#L3

The iterable should be used directly instead of converting to an array. It would have the benefit of better supporting generated sequences.

A pull request would be wonderful 🙌🌟

**Comment by parro-it** [comment]
Awesome work with all the promise repos :cool: :+1: 
I would like to write a PR, I was thinking to suggest you the same change while reading your code, then I saw this issue :smiley:
