### ISSUE TITLE
Typescript typings

### ISSUE THREAD

**Issue by kirillgroshkov** [sindresorhus/p-map#14]
I'm having issues with non-bundled typings from `@types/p-map`, it'll be easier if they are bundled and `import * as pMap from 'p-map'` just works.

I've noticed in e.g Ky and `p-throttle` typings are now bundled with the package, would be nice to have it here too.

**Comment by kirillgroshkov** [comment]
Noticed the PR just now: https://github.com/sindresorhus/p-map/pull/13

**Comment by sindresorhus** [comment]
Closing in favor of #13
