### ISSUE TITLE
type inference in vscode with pure javascript doesn't work

### ISSUE THREAD

**Issue by 5c077yP** [sindresorhus/p-map#15]
Hey, 

i saw with #13 typescript bindings were added. I'm also a using this lib quite often + work with vscode, but it seems the type inference does not work with pure javascript. Here's an example:

```js
const test = () => {
  const myList = [1,2,3,4];
  return pmap(myList, (item) => item * 3)
}
```

For the functions return value i just get `any` (not even Promise<any>).

Doing similar with e.g. `_.map` works, so i assume somehow we can get this running with js. I haven't written `d.ts` files before, so not sure what's actually causing this?

Thanks for this great lib btw.

**Comment by SamVerschueren** [comment]
Try importing the package like this

```js
const pMap = require('p-map').default;
```

Supporting both ESM and CJS in type definitions is just not possible.

**Comment by 5c077yP** [comment]
thanks, that was it 👍 , will close this issue then.
