### ISSUE TITLE
Support Async Iterable Protocol

### ISSUE THREAD

**Issue by kuchta** [sindresorhus/p-map#20]

**Comment by sindresorhus** [comment]
Please include some body text in the issue. For example, what it would look like to support this?

**Comment by kuchta** [comment]
I meant it would be cool to have support for Async Iterables in place of input argument.

**Comment by sindresorhus** [comment]
Yeah, we could do this, but not worth doing it until we can use it natively internally, which means targeting Node.js 10, which we can not do until next year.

**Comment by sindresorhus** [comment]
This can now be done. PR welcome :)
