### ISSUE TITLE
p-map v3.0.0 does not work with react-native

### ISSUE THREAD

**Issue by mieszko4** [sindresorhus/p-map#22]
After upgrade the following error shows:
```
Loading dependency graph, done.
error: bundling failed: Error: Unable to resolve module `os` from `[..]/node_modules/clean-stack/index.js`: Module `os` does not exist in the Haste module map
```

I am using android with react-native v0.59.10

**Comment by doesdev** [comment]
Yeah, unfortunately it seems the `stopOnError` implementation requires `clean-stack` which isn't browser friendly (at least without adding polyfills).

**Comment by mieszko4** [comment]
Actually, after another try it does seem to work for me. I guess it was caused by some caching so I will close this one
