### ISSUE TITLE
How can I add delay?

### ISSUE THREAD

**Issue by dilipkumar2k6** [sindresorhus/p-map#25]
Between two consecutive call, I would like to add `delay`, is it possible?

**Comment by sindresorhus** [comment]
The `mapper` waits for a promise/async-function, so you can use https://github.com/sindresorhus/delay in there.

```js
(async () => {
	const mapper = async element => {
		// something here

		await delay(1000);

		// something here
	};

 	const result = await pMap(array, mapper, {concurrency: 2});
})();
```
