### ISSUE TITLE
Compare with Promise.all()

### ISSUE THREAD

**Issue by BanYeung** [sindresorhus/p-map#27]
I think pMap() has the same behavior with the built-in Promise.all(). Am I right?
And further more, what is pMap()'s advantage, in other words, why or when we should use pMap() instead of the built-in Promise.all()?

Can anyone answer my question?

Forgive my poor English...

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/p-map/commit/76de3060bf80bd904f27d33da3ff814ba149056c
