### ISSUE TITLE
Should be able to get resolved values when stopOnError=false

### ISSUE THREAD

**Issue by wholenews** [sindresorhus/p-map#29]
Should be able to get both resolved values, and aggregate error, like in `p-settle`.  I'm looking for the combination of `p-settle` and `p-map` which seems not to exist... 

With `p-settle` (even when supplying function) it's called immediately.  In my case this starts all the requests at once.

With `p-map` it throttles the requests according to `concurrency` but there is no way to get the resolved results if any request fails.

**Comment by sindresorhus** [comment]
The `concurrency` option in `p-settle` should work: https://github.com/sindresorhus/p-settle/blob/071020fc6cd7884e74228d546943f53cbc3ca28c/test.js#L31 And if not, that's a bug.

You could also use https://github.com/sindresorhus/p-reflect with `p-map`.

**Comment by wholenews** [comment]
Ah, you're right `p-settle` does work as intended. I must have misinterpreted the data. Thanks for a quick response!
