### ISSUE TITLE
p-flat-map

### ISSUE THREAD

**Issue by MajorBreakfast** [sindresorhus/p-map#30]
I encountered the need for `p-flat-map`. Here's what I came up with:

```ts
const pFlatMap = async <Element, NewElements>(
  input: Iterable<Element>,
  mapper: pMap.Mapper<Element, NewElements>,
  options?: pMap.Options
): Promise<FlatArray<NewElements[], 1>[]> => {
  const mapped: NewElements[] = await pMap(input, mapper, options)
  return mapped.flat()
}
```

Usage example:
```ts
const products = await pFlatMap(categories, listProductsForCategory, { concurrency: 50 })
```

Would it be possible to add this to the collection?

**Comment by sindresorhus** [comment]
Why not just `(await pMap(…)).flat()`?

**Comment by MajorBreakfast** [comment]
I used `pFlatMap` for better readability. With `(await pMap(…)).flat()` the intention behind the code was less obvious.

**Comment by sindresorhus** [comment]
I personally think the intention is quite clear, even more so than `pFlatMap`.

**Comment by septatrix** [comment]
> Why not just `(await pMap(…)).flat()`?

Apart from the IMO worse readability due to the required parentheses there is also the disadvantage of requiring slightly more memory. That, however, would also not be solved by the simple implementation proposed above but would require touching more code

**Comment by septatrix** [comment]
> Why not just `(await pMap(…)).flat()`?

Another limitation which more people might be stumble upon is that this simply not possible when using `pMapIterable`. In those cases one has to construct a nested loop which is definitely less readable than `pFlatMapIterable`
