### ISSUE TITLE
Undefined items added to resulting mapped collection

### ISSUE THREAD

**Issue by mlaflamm** [sindresorhus/p-map#4]
Random `undefined` items are added to my mapped array with version 1.1.0. I don't have the same issue with version 1.0.0 or with bluebird. I've been able to consistently reproduce the issue with the following test. The same test works with concurrency 1 or concurrency >= `myInput.length`. 

```
test('async with concurrency: 2', async t => {
	const myInput = [100, 200, 10, 36, 13, 45];
	const myMapper = value => {
		return new Promise(resolve => {
			setTimeout(() => resolve(value), value);
		});
	};

	t.deepEqual(await m(myInput, myMapper, {concurrency: 2}), myInput);
});
```

It is not obvious to see the extra undefined items with the ava output (I've never used ava before) but my mocha/chai version of the test is showing this output:

```
AssertionError: expected [ 100, 200, 10, , 36, , 13, , 45 ] to deeply equal [ 100, 200, 10, 36, 13, 45 ]
      + expected - actual

       [
         100
         200
         10
      -  [undefined]
         36
      -  [undefined]
         13
      -  [undefined]
         45
       ]

```

**Comment by sindresorhus** [comment]
Seems to be [array holes](http://www.2ality.com/2015/09/holes-arrays-es6.html) rather than `undefined`.

@parro-it Any ideas? Seems it was introduced with https://github.com/sindresorhus/p-map/commit/7e7c6b6d02d35daaf9e9f3441a0328f3f1f14a62.

**Comment by parro-it** [comment]
I'm receiving the same result as @mlaflamm. 
I will investigate the cause todaY

**Comment by parro-it** [comment]
The problem was related to how we calculate the index of each element of the input array: 
they now have to be strictly sequential, because we access the input array as an iterable.

This caused a misalignment between input and output index, that was causing the array holes.
My PR #5 should solve the problem.
