### ISSUE TITLE
It is neccessary to have common.js export

### ISSUE THREAD

**Issue by brandonxiang** [sindresorhus/p-map#55]
`main` field is needed in the packge.json. I want to build a tool using p-map.

[lukeed/bundt](https://github.com/lukeed/bundt) map help

**Comment by sindresorhus** [comment]
This is a problem with your build tool, not this package. The `exports` field replaces `main`.

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by brandonxiang** [comment]
> This is a problem with your build tool, not this package. The `exports` field replaces `main`.

I used tsup as build tool
