### ISSUE TITLE
Browser Compatibility with `^5.0.0`

### ISSUE THREAD

**Issue by rwv** [sindresorhus/p-map#59]
After upgrading to ^5.0.0, vite got an error: 
```
browser-external:os:3 Uncaught Error: Module "os" has been externalized for browser compatibility and cannot be accessed in client code.
    at Object.get (browser-external:os:3:11)
    at index.js:6:27
```

After some digging, this is related to `aggregate-error  ^4.0.0`'s dep `clean-stack ^4.0.0` 

[`import os from 'os'` (index.js#L1)](https://github.com/sindresorhus/clean-stack/blob/b09f9796fc87667c8b58631b91b5d41ce5dccc12/index.js#L1)

I wonder could `homedir` be implemented in a browser-friendly way?

I don't  know which repo is the most suitable place to open this issue, please transfer to the right place if needed.

Thank you!

**Comment by rwv** [comment]
Oh! I found that similar issue had already be opened. Sorry for interrupt.
https://github.com/sindresorhus/clean-stack/issues/28

**Comment by furudean** [comment]
I maintain a fork of this which has the `aggregate-error` dependency patched out in favor of the native implementation. https://github.com/furudean/p-map

**Comment by silverwind** [comment]
Should be properly fixed once https://github.com/sindresorhus/p-map/issues/64 is resolved.
