### ISSUE TITLE
p-map v5.5.0 have some probloem in the dependencies : aggregate-error

### ISSUE THREAD

**Issue by Navi-1993** [sindresorhus/p-map#61]
![image](https://user-images.githubusercontent.com/49209493/178719821-61f760d5-993f-40c6-bdaa-dca234697bce.png)

I find the error line in local file 
![image](https://user-images.githubusercontent.com/49209493/178721139-9b9df5bd-8931-4569-8719-e5f11ecbc627.png)

**Comment by sindresorhus** [comment]
This is a problem with your Webpack config or Webpack version. That syntax is completely valid JS syntax.

**Comment by Navi-1993** [comment]
ohhh, it was a new feature in es2022
