### ISSUE TITLE
Issue when trying to compile a react project using p-map

### ISSUE THREAD

**Issue by mfyz** [sindresorhus/p-map#7]
Hi, I used p-map on my react application and when I'm trying to build production package, it fails with following output:

```
> react-scripts build

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

 	./node_modules/p-map/index.js:2

Read more here: http://bit.ly/2tRViJ9
```

Suggestion being, publishing package in npm with pre-compiled version included in the package. Does it makes sense? Can you do it?

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

I'm sorry that `create-react-app` is lacking in this aspect, but it's up to them to support the community. Each package should not be required to specially support `create-react-app`. Please do open an issue on `create-react-app` about this pain-point.
