### ISSUE TITLE
Memory leak when using abort signals

### ISSUE THREAD

**Issue by dbas-dn** [sindresorhus/p-map#75]
We have encountered a memory leak issue. After an extensive search for the source of the leak, it was found that it occurred in pMap. Upon reviewing the source code of your package, I discovered that you subscribe to the AbortSignal event but do not unsubscribe from it, which causes the memory leak.

**Comment by sindresorhus** [comment]
// @jopemachine

**Comment by liuhanqu** [comment]
@sindresorhus  use `FinalizationRegistry` and the target is the return promise ?

**Comment by sindresorhus** [comment]
@liuhanqu That's not needed in this case. We know when `p-map` finishes, so we can just put a cleanup handler after it's done.
