### ISSUE TITLE
Consider rejecting only on rejected Promises.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [sindresorhus/p-map#8]
According to the documentation, `pMap` returns
> a Promise that is fulfilled when all promises in input and ones returned from mapper are fulfilled, or rejects if any of the promises reject.

But strictly speaking, it's
> a Promise that is fulfilled when all promises in input and ones returned from mapper are fulfilled, or rejects if any of the promises reject, or `mapper` or `options.concurrency` are invalid, or `mapper` throws.

It's a subtle difference, especially if you're awaiting `pMap` or passing an async function as `mapper`.

**Comment by sindresorhus** [comment]
What would be the alternative here? If you're going to say, synchronously throwing, that's a no-go, as promises should always reject.

**Comment by wtgtybhertgeghgtwtg** [comment]
Something like
```
pMap(['foo']); // Throws
pMap(['foo'], () => Promise.reject()); // Rejects
```
I guess I am suggesting throwing synchronously, but I would say that the Promise still always resolves or rejects, but the function that returns the Promise can throw.

**Comment by sindresorhus** [comment]
See: https://twitter.com/jaffathecake/status/638659818996269056

**Comment by wtgtybhertgeghgtwtg** [comment]
I did not know that.  Sorry for the bother.

**Comment by sindresorhus** [comment]
No worries. I did not know either before that tweet :)
